name: super_better_auth
description: A Dart/Flutter client for the Better Auth platform, enabling secure sign-in, sign-up, and session management in Flutter applications.
version: 1.0.1
homepage: https://github.com/supersyntx/super_better_auth.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^5.0.0-alpha.3
  freezed_annotation: ^3.0.0
  hive: ^2.2.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  retrofit: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  build_runner: ^2.4.15
  retrofit_generator: ^9.3.0

flutter:
